### ISSUE TITLE
搜索范围限定在窗口显示内容

### ISSUE THREAD

**Issue by pysnow530** [noearc/leap-zh.nvim#6]
当前搜索范围是窗口关联的整个buffer，有如下几个问题：

1. 匹配结果过多，个数更可能超过 `leap` 的 `safe_labels`（默认17），导致 `autojump` 特性失效（但是多出屏幕的搜索基本无效）
2. 匹配内容多导致性能下降（对我影响不大）

对于超出屏幕的内容，更适合vim默认的多字符搜索 `/` 或者 `<c-d>`

建议仍然保持 `leap` 的默认设定，只支持选择可视范围内的文本

**Comment by pysnow530** [comment]
代码提交：https://github.com/neo451/leap-zh.nvim/pull/7

**Comment by neo451** [comment]
感谢！

**Comment by pysnow530** [comment]
@neo451 客气了，我也是自己用的特性，顺手提交了。很棒的插件，解决了我的问题 👍
